# Generated by Django 4.2.17 on 2024-12-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
